project:
  type: default
  output-dir: _output

format:
  pdf:
    documentclass: article
    geometry: margin=1in
    fontsize: 11pt
    keep-tex: false
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  echo: true
  warning: false
  error: false
  cache: true
